ESLegendsASPMVC/src/ElderScrollsLegendsDB/Controllers/AttributesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace ElderScrollsLegendsDB.Controllers
{
    public class AttributesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Agility()
        {
            return View();
        }

        public IActionResult Endurance()
        {
            return View();
        }

        public IActionResult Intelligence()
        {
            return View();
        }

        public IActionResult Strength()
        {
            return View();
        }

        public IActionResult Willpower()
        {
            return View();
        }

        public IActionResult Neutral()
        {
            return View();
        }

        [ActionName("Dual-Attribute")]
        public IActionResult DualAttribute()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Controllers/ClassesController.cs
using Microsoft.AspNet.Mvc;

namespace ElderScrollsLegendsDB.Controllers
{
    public class ClassesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Archer()
        {
            return View();
        }

        public IActionResult Assassin()
        {
            return View();
        }

        public IActionResult Battlemage()
        {
            return View();
        }

        public IActionResult Crusader()
        {
            return View();
        }

        public IActionResult Mage()
        {
            return View();
        }

        public IActionResult Monk()
        {
            return View();
        }

        public IActionResult Scout()
        {
            return View();
        }

        public IActionResult Sorceror()
        {
            return View();
        }

        public IActionResult Spellsword()
        {
            return View();
        }

        public IActionResult Warrior()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Controllers/GuidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ElderScrollsLegendsDB.Controllers
{
    public class GuidesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [ActionName("Understanding-Lanes")]
        public IActionResult UnderstandingLanes()
        {
            return View();
        }

        [ActionName("Arena-Tickets")]
        public IActionResult ArenaTickets()
        {
            return View();
        }

        [ActionName("Card-Packs")]
        public IActionResult CardPacks()
        {
            return View();
        }


    }
}

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Controllers/RacesController.cs
using Microsoft.AspNet.Mvc;

namespace ElderScrollsLegendsDB.Controllers
{
    public class RacesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Argonian()
        {
            return View();
        }

        public IActionResult Breton()
        {
            return View();
        }

        [ActionName("Dark-Elf")]
        public IActionResult DarkElf()
        {
            return View();
        }

        [ActionName("High-Elf")]
        public IActionResult HighElf()
        {
            return View();
        }

        public IActionResult Imperial()
        {
            return View();
        }

        public IActionResult Khajiit()
        {
            return View();
        }

        public IActionResult Nord()
        {
            return View();
        }

        public IActionResult Orc()
        {
            return View();
        }

        public IActionResult Redguard()
        {
            return View();
        }

        [ActionName("Wood-Elf")]
        public IActionResult WoodElf()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Views/Guides/Arena-Tickets.cshtml
@{
    ViewData["Title"] = "Arena Tickets";
}


<div class="row">
    <div class="col-md-12">

        <h2 class="">@ViewData["Title"]</h2>

        <h4>WIP</h4>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>

    </div>
</div>

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Views/Guides/Card-Packs.cshtml
@{
    ViewData["Title"] = "Card Packs";
}


<div class="row">
    <div class="col-md-12">

        <h2 class="">@ViewData["Title"]</h2>

        <h4>WIP</h4>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>


    </div>
</div>

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Views/Guides/Index.cshtml
@{
    ViewData["Title"] = "Guides and Tutorials";
}

<div class="row">
    <div class="col-md-12">

        <h2 class="">@ViewData["Title"]</h2>

        <h4>Game Basics</h4>

        <ul class="list-group">
            <li class="list-group-item"><a asp-action="Index" asp-controller="Attributes">Attributes</a></li>
            <li class="list-group-item"><a asp-action="Index" asp-controller="Classes">Classes</a></li>
            <li class="list-group-item"><a asp-action="Index" asp-controller="Races">Races</a></li>
        </ul>

        <h4>Beginner Guides</h4>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>

        <ul class="list-group">
            <li class="list-group-item"><a asp-action="Understanding-Lanes" asp-controller="Guides">Understanding Lanes in Elder Scrolls Legends</a></li>
            <li class="list-group-item"><a asp-action="Card-Packs" asp-controller="Guides">Card Packs</a></li>
            <li class="list-group-item"><a asp-action="Arena-Tickets" asp-controller="Guides">Arena Tickets</a></li>
        </ul>


    </div>
</div>

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Views/Guides/Understanding-Lanes.cshtml
@{
    ViewData["Title"] = "Understanding Lanes";
}


<div class="row">
    <div class="col-md-12">

        <h2 class="">@ViewData["Title"]</h2>

        <h4>WIP</h4>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae ante non sapien consectetur imperdiet. Suspendisse potenti. Praesent urna nisl, fermentum quis urna convallis, gravida ullamcorper purus. Sed vitae malesuada libero, ac blandit mi. Vivamus tincidunt mauris eros. Ut vitae aliquam ligula, a ultricies sem. Morbi molestie ante ut felis faucibus, eu sagittis orci pretium. Nulla facilisi. Vivamus mattis arcu lacus, at malesuada erat imperdiet a. Morbi eros metus, accumsan a lacinia ac, pulvinar ut arcu. Donec id mauris magna.
        </p>


    </div>
</div>