ESLegendsASPMVC/src/ElderScrollsLegendsDB/Controllers/CardsController.cs
using System;
using Microsoft.AspNet.Mvc;
using ElderScrollsLegendsDB.Models;
using System.Linq;
using System.Collections.Generic;
using ElderScrollsLegendsDB.ViewModels;

using Microsoft.Data.Entity;

namespace ElderScrollsLegendsDB.Controllers
{
    public class CardsController : Controller
    {

        private ApplicationDbContext _context;

        //private EslDbRepository eslDbRepo;

        public CardsController(ApplicationDbContext context)
        {
            _context = context;
            
            //EslDbRepo way of doing things... 
            //eslDbRepo = new EslDbRepository(context);
        }


        /// <summary>
        /// DEV ONLY - automation of creating a card's file name
        /// Example:
        /// card name: Dark Elf Wizard
        /// card image name generated: Dark-Elf-Wizard.jpg
        /// </summary>
        public void GenerateCardArtFileNameToDatabase()
        {
            var model = GetAllCards();

            //get all image file names from wwwroot\images
            var imageNames = System.IO.Directory.GetFiles("wwwroot\\images\\cards");

            foreach (var card in model)
            {
                //if (String.IsNullOrEmpty(card.ArtFullResFileName))
                //{
                if (imageNames.Contains("wwwroot\\images\\cards\\" + CreateArtFullResFileName(card.CardName)))
                {
                    card.ArtFullResFileName = CreateArtFullResFileName(card.CardName);
                    card.ArtThumbnailFileName = CreateArtThumbnailFileName(card.CardName);

                    _context.Update(card);
                    _context.SaveChanges();
                }
                else
                {
                    card.ArtFullResFileName = "aaa_template.jpg";
                    card.ArtThumbnailFileName = "aaa_template_thumb.jpg";

                    _context.Update(card);
                    _context.SaveChanges();
                }
                //}
            }
        }


        /// <summary>
        /// The main index page - displays all cards in the database as a list of details or a list of images 
        /// </summary>
        /// <param name="sortOrder"></param>
        /// <param name="searchQuery"></param>
        /// <returns></returns>
        public IActionResult Index(string sortOrder, string searchQuery)
        {
            //#warning GenerateCardArtFileNameToDatabase wew lad
            GenerateCardArtFileNameToDatabase();

            var model = new List<Card>();

            model = GetAllCards();


            //search
            if (!String.IsNullOrEmpty(searchQuery))
            {
                searchQuery = searchQuery.ToLower();

                model = model.Where(c => c.CardName.ToLower().Contains(searchQuery)).ToList();
            }

            #region Sorting
            //ternary toggles for sorting
            ViewBag.SortByName =            (String.IsNullOrEmpty(sortOrder) || sortOrder == "ByName_asc") ? "ByName_desc" : "ByName_asc";
            ViewBag.SortByAttributeType =   (sortOrder == "ByAttributeType_asc") ? "ByAttributeType_desc" : "ByAttributeType_asc";
            ViewBag.SortByCardType =        (sortOrder == "ByCardType_asc") ? "ByCardType_desc" : "ByCardType_asc";
            ViewBag.SortByManaCost =        (sortOrder == "ByManaCost_asc") ? "ByManaCost_desc" : "ByManaCost_asc";
            ViewBag.SortByAttack =          (sortOrder == "ByAttack_asc") ? "ByAttack_desc" : "ByAttack_asc";
            ViewBag.SortByDefense =         (sortOrder == "ByDefense_asc") ? "ByDefense_desc" : "ByDefense_asc";
            ViewBag.SortByRarityType =      (sortOrder == "ByRarityType_asc") ? "ByRarityType_desc" : "ByRarityType_asc";

            //Sort based on the sort order
            //TODO: make someting get all cards and return the result via JSON - then do the sorting on the
            //clients browser to save lots of CPU time.
            //Sorting here usually takes the sort requested (like attribute) then sorts based on that then by card.CardName
            switch (sortOrder)
            {
                case "ByName_asc":
                    model = model.OrderBy(c => c.CardName).ToList();
                    break;
                case "ByName_desc":
                    model = model.OrderByDescending(c => c.CardName).ToList();
                    break;
                case "ByAttributeType_asc":
                    model = model.OrderBy(c => c.Attribute.AttributeType).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByAttributeType_desc":
                    model = model.OrderByDescending(c => c.Attribute.AttributeType).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByCardType_asc":
                    model = model.OrderBy(c => c.CardType.CardTypeValue).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByCardType_desc":
                    model = model.OrderByDescending(c => c.CardType.CardTypeValue).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByManaCost_asc":
                    model = model.OrderBy(c => c.ManaCost).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByManaCost_desc":
                    model = model.OrderByDescending(c => c.ManaCost).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByAttack_asc":
                    model = model.OrderBy(c => c.Attack).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByAttack_desc":
                    model = model.OrderByDescending(c => c.Attack).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByDefense_asc":
                    model = model.OrderBy(c => c.Defense).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByDefense_desc":
                    model = model.OrderByDescending(c => c.Defense).ThenBy(c => c.CardName).ToList();
                    break;
                //using RarityID for a proper sort
                case "ByRarityType_asc":
                    model = model.OrderBy(c => c.RarityID).ThenBy(c => c.CardName).ToList();
                    break;
                case "ByRarityType_desc":
                    model = model.OrderByDescending(c => c.RarityID).ThenBy(c => c.CardName).ToList();
                    break;
                default:
                    model = model.OrderBy(c => c.CardName).ToList();
                    break;
            }

            #endregion

            return View(model);
        }


        /// <summary>
        /// Get All Cards
        /// </summary>
        /// <returns>List of Cards from the database</returns>
        public List<Card> GetAllCards()
        {
            //using Microsoft.Data.Entity; -- the Include ext method for fk
            var cards = _context.Card.Include(c => c.Attribute)
                                    .Include(c => c.CardType)
                                    .Include(c => c.Rarity)
                                    .ToList();

            return cards;
        }


        /// <summary>
        /// Calls the GetAllCards() method then returns that List of type Card as JSON 
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAllCardsAsJson()
        {
            return Json(GetAllCards());
        }


        /// <summary>
        /// Returns a single Card object by its CardID
        /// </summary>
        /// <param name="cardID"></param>
        /// <returns></returns>
        public Card GetCardByCardID(int cardID)
        {
            //using Microsoft.Data.Entity; -- the Include ext method
            var card = _context.Card.Where(c => c.CardID == cardID)
                                    .Include(c => c.Attribute)
                                    .Include(c => c.CardType)
                                    .Include(c => c.Rarity)
                                    .FirstOrDefault();

            return card;
        }


        /// <summary>
        /// remove space, comma, and quote ' char from name then trim it. then append .jpg
        /// </summary>
        /// <returns>a string to be used as the full res art image filename</returns>
        public string CreateArtFullResFileName(string cardName)
        {
            cardName = cardName.Replace(' ', '-').Replace('\'', '-').Replace(',', '-').Trim();

            cardName += ".jpg";

            return cardName;
        }

        /// <summary>
        /// remove space, comma, and quote ' char from name then trim it. then append _thumb.jpg
        /// </summary>
        /// <returns>a string to be used as the thumbnail art image filename</returns>
        public string CreateArtThumbnailFileName(string cardName)
        {
            cardName = cardName.Replace(' ', '-').Replace('\'', '-').Replace(',', '-').Trim();

            cardName += "_thumb.jpg";

            return cardName;
        }



        /// <summary>
        /// Shows the details of a Card
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            //set CardID to 0 if null
            int cardID = id ?? 0;

            if (id > 0 && ModelState.IsValid)
            {
                //Card card = _context.Card.Single(c => c.CardID == id);

                Card card = GetCardByCardID(cardID);

                if (card == null)
                {
                    return View("NotFound");
                }

                return View(card);
            }
            else
            {
                return View("Error");
            }
        }


        /// <summary>
        /// Create a card to add to database form
        /// </summary>

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Controllers/DecksController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Mvc;
using ElderScrollsLegendsDB.Models;
using ElderScrollsLegendsDB.ViewModels;

using Microsoft.Data.Entity;

namespace ElderScrollsLegendsDB.Controllers
{
    public class DecksController : Controller
    {

        private ApplicationDbContext _context;

        public DecksController(ApplicationDbContext context)
        {
            _context = context;
        }


        /// <summary>
        /// Build a basic DeckViewModel based on a deckID
        /// Does NOT add card objects.
        /// </summary>
        /// <param name="deckID"></param>
        /// <returns></returns>
        public DeckViewModel DeckBuilder(Deck deck)
        {

            var deckViewModel = new DeckViewModel(deck);

            //get all cardIDs that belong to this deckID
            var deckToCardsMap = _context.DeckToCardsMap.Where(d => d.DeckID == deckViewModel.DeckID);

            foreach (var deckToCard in deckToCardsMap)
            {

                deckViewModel.CardIDs.Add(deckToCard.CardID);
            }

            return deckViewModel;
        }



        // GET: /<controller>/
        /// <summary>
        /// Get all DeckIDs then build a DeckViewModel then add it to a list for view to display each decks
        /// a deck's cards are not generated here. Just the IDs are added
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var allDeckIDs = _context.Deck.ToList().Select(d => d.DeckID);

            var model = new List<DeckViewModel>();
            foreach (var deckID in allDeckIDs)
            {
                var deck = _context.Deck
                                    .Include(d => d.User)
                                    .Where(d => d.DeckID == deckID).FirstOrDefault();

                if(deck == null)
                {
                    return HttpNotFound();
                }

                var deckVM = DeckBuilder(deck);

                model.Add(deckVM);
            }

            return View(model);
        }



        /// <summary>
        /// Details of a Deck
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            //cards added here not in deck builder for slight optimization
            if (id > 0 && ModelState.IsValid)
            {
                //int? to int::deckID
                int deckID = id ?? 1;

                var deck = _context.Deck.Where(d => d.DeckID == deckID).FirstOrDefault();

                //if no deck was found ie like a deckID is not in the database
                if (deck == null)
                {
                    return HttpNotFound();
                }

                DeckViewModel deckVM = DeckBuilder(deck);

                //build each card to add to the deck.Cards Card collection
                foreach (var cardID in deckVM.CardIDs)
                {
                    var card = _context.Card.Where(c => c.CardID == cardID)
                        .Include(c => c.Attribute)
                        .Include(c => c.CardType)
                        .Include(c => c.Rarity)
                        .FirstOrDefault();

                    deckVM.Cards.Add(card);
                }

                deckVM.Cards = deckVM.Cards.OrderBy(c => c.CardName).ToList();

                return View(deckVM);
            }
            else
            {
                return View("Error");
            }
        }

    }
}

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Controllers/GuidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ElderScrollsLegendsDB.Controllers
{
    public class GuidesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [ActionName("Understanding-Lanes")]
        public IActionResult UnderstandingLanes()
        {
            return View();
        }

        [ActionName("Arena-Tickets")]
        public IActionResult ArenaTickets()
        {
            return View();
        }

        [ActionName("Card-Packs")]
        public IActionResult CardPacks()
        {
            return View();
        }


    }
}

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Controllers/RacesController.cs
using Microsoft.AspNet.Mvc;

namespace ElderScrollsLegendsDB.Controllers
{
    public class RacesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Argonian()
        {
            return View();
        }

        public IActionResult Breton()
        {
            return View();
        }

        [ActionName("Dark-Elf")]
        public IActionResult DarkElf()
        {
            return View();
        }

        [ActionName("High-Elf")]
        public IActionResult HighElf()
        {
            return View();
        }

        public IActionResult Imperial()
        {
            return View();
        }

        public IActionResult Khajiit()
        {
            return View();
        }

        public IActionResult Nord()
        {
            return View();
        }

        public IActionResult Orc()
        {
            return View();
        }

        public IActionResult Redguard()
        {
            return View();
        }

        [ActionName("Wood-Elf")]
        public IActionResult WoodElf()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Resource or Page not Found";
}

@* custom not found page? is this needed or is there a built in one via some ActionResult return? *@

<div class="row">
    <div class="col-md-12">

        <h1 class="text-danger text-center">@ViewData["Title"]</h1>
        <h2 class="text-danger text-center">404</h2>
        <h3 class="text-danger text-center">The page you requested was not found.</h3>

    </div>
</div>

ESLegendsASPMVC/src/ElderScrollsLegendsDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - ElderScrollsLegendsDB</title>

        <link rel="icon" type="image/png" href="~/images/icon_thumb.png">

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
        @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)

        @*@RenderSection("head", required: false)*@
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">ElderScrollsLegendsDB</a>
                </div>
                @* for submenu https://github.com/vsn4ik/bootstrap-submenu *@
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="View Game information - Attributes, Classes, Races">Game Information <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Attributes" asp-action="Index">Attributes</a></li>
                                <li><a asp-controller="Classes" asp-action="Index">Classes</a></li>
                                <li><a asp-controller="Races" asp-action="Index">Races</a></li>
                            </ul>
                        </li>

                        @*<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="View Attribute information">Attributes <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Attributes" asp-action="Index">Attributes</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-controller="Attributes" asp-action="Agility">Agility</a></li>
                                <li><a asp-controller="Attributes" asp-action="Endurance">Endurance</a></li>
                                <li><a asp-controller="Attributes" asp-action="Intelligence">Intelligence</a></li>
                                <li><a asp-controller="Attributes" asp-action="Strength">Strength</a></li>
                                <li><a asp-controller="Attributes" asp-action="Willpower">Willpower</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="View Race information">Races <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Races" asp-action="Index">Races</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-controller="Races" asp-action="Argonian">Argonian</a></li>
                                <li><a asp-controller="Races" asp-action="Breton">Breton</a></li>
                                <li><a asp-controller="Races" asp-action="Dark-Elf">Dark Elf</a></li>
                                <li><a asp-controller="Races" asp-action="High-Elf">High Elf</a></li>
                                <li><a asp-controller="Races" asp-action="Imperial">Imperial</a></li>
                                <li><a asp-controller="Races" asp-action="Khajiit">Khajiit</a></li>
                                <li><a asp-controller="Races" asp-action="Nord">Nord</a></li>
                                <li><a asp-controller="Races" asp-action="Orc">Orc</a></li>
                                <li><a asp-controller="Races" asp-action="Redguard">Redguard</a></li>
                                <li><a asp-controller="Races" asp-action="Wood-Elf">Wood Elf</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="View Class information">Classes <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Classes" asp-action="Index">Classes</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-controller="Classes" asp-action="Archer">Archer</a></li>
                                <li><a asp-controller="Classes" asp-action="Assassin">Assassin</a></li>
                                <li><a asp-controller="Classes" asp-action="Battlemage">Battlemage</a></li>
                                <li><a asp-controller="Classes" asp-action="Crusader">Crusader</a></li>
                                <li><a asp-controller="Classes" asp-action="Mage">Mage</a></li>
                                <li><a asp-controller="Classes" asp-action="Monk">Monk</a></li>
                                <li><a asp-controller="Classes" asp-action="Scout">Scout</a></li>
                                <li><a asp-controller="Classes" asp-action="Spellsword">Spellsword</a></li>
                                <li><a asp-controller="Classes" asp-action="Warrior">Warrior</a></li>
                            </ul>
                        </li>*@

                        <li><a asp-controller="Cards" asp-action="Index" title="View and search for cards">Cards</a></li>
                        <li><a asp-controller="Decks" asp-action="Index" title="View decks created by users">Decks</a></li>
                        @*<li><a asp-controller="Decks" asp-action="Index" title="Build a deck">Build a Deck</a></li>*@
                        <li><a asp-controller="Guides" asp-action="Index" title="Guides and Tutorials">Guides</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-controller="Home" asp-action="About">About/FAQ</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>

                </div>
            </div>
        </div>
        <div class="container body-content" style="min-height:720px;">
            @RenderBody()
        </div>

        <footer class="footer">
            <div class="container text-center">
                <p></p>
                <p>&copy; 2017 - ElderScrollsLegendsDB</p>
                <p><a asp-controller="Home" asp-action="About">About/FAQ</a></p>
                <p><a asp-controller="Home" asp-action="Contact">Contact</a></p>
            </div>
        </footer>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>